### ISSUE TITLE
Lack data and python file while running code

### ISSUE THREAD

**Issue by nguyentthong** [uclanlp/Robust-XLT#1]
Hi @ej0cl6,

Your work has galvanized me so greatly that I tried running your code. However, when I executed perturbation for xnli task, it printed out the error "FileNotFoundError: [Errno 2] No such file or directory: './data/data_generalized/xnli/test-en.tsv'".

Moreover, for the training script, I could not find run_classify.py file. 

I look forward to hearing from you soon since this is quite an interesting work for me.
Regards.

**Comment by ej0cl6** [comment]
Hi @nguyentthong,

Thanks for reporting this issue. I have updated the data. 

For the `run_classify.py`, according to https://github.com/uclanlp/Robust-XLT/blob/master/scripts/train_xnli.sh#L51, you can find it under the `$PWD/third_party/` directory.

Thanks.
