### ISSUE TITLE
the function of adversarial training

### ISSUE THREAD

**Issue by haoyu0408** [uclanlp/Robust-XLT#2]
Hi, would you like to tell me where is the function of adversarial training? I did not find it. Thanks!

**Comment by ej0cl6** [comment]
Hi, thanks for asking. Currently, this code only supports randomize smoothing with data augmentation because it's the most effective method that has consistent improvements over different tasks in our paper. We will consider adding the code for adversarial training.

**Comment by haoyu0408** [comment]
> 

Thanks for your help!
